version: '3.4'

services:
  basketdbmongo:
    image: mongo

  coupondb:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

volumes:
  mongo_data:
